// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// acf_no_center
NumericMatrix acf_no_center(NumericMatrix data, int lag);
RcppExport SEXP _fnets_acf_no_center(SEXP dataSEXP, SEXP lagSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type lag(lagSEXP);
    rcpp_result_gen = Rcpp::wrap(acf_no_center(data, lag));
    return rcpp_result_gen;
END_RCPP
}
// truncateAndComputeCovariance_lag
NumericMatrix truncateAndComputeCovariance_lag(NumericMatrix data, NumericVector tau, int lag);
RcppExport SEXP _fnets_truncateAndComputeCovariance_lag(SEXP dataSEXP, SEXP tauSEXP, SEXP lagSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< int >::type lag(lagSEXP);
    rcpp_result_gen = Rcpp::wrap(truncateAndComputeCovariance_lag(data, tau, lag));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fnets_acf_no_center", (DL_FUNC) &_fnets_acf_no_center, 2},
    {"_fnets_truncateAndComputeCovariance_lag", (DL_FUNC) &_fnets_truncateAndComputeCovariance_lag, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_fnets(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
