# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

acf_no_center <- function(data, lag = 0L) {
    .Call(`_fnets_acf_no_center`, data, lag)
}

truncateAndComputeCovariance_lag <- function(data, tau, lag = 0L) {
    .Call(`_fnets_truncateAndComputeCovariance_lag`, data, tau, lag)
}

